spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5433/nuclear2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088

system:
  images: G:/sasmac/images
  untargz: G:/sasmac/untargz
  datasource: G:/sasmac/data,E:/sasmac/data,G:/data

#  username: postgres
#  password: postgres
#  url: jdbc:postgresql://hexi_postgres:5440/nuclear
