spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/nuclear_real
    tomcat:
      max-active: 2048
      min-idle: 512
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8688

system:
  files: D:\sasmac\files
  untargz: D:\sasmac\untargz
  datasource: F:\sasmac,\\172.16.18.201\zionNAS

