spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/nuclear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

server:
  port: 8088

system:
  images: D:/sasmac/images
  untargz: D:/sasmac/untargz
  datasource: D:/sasmac/data,E:/sasmac/data

#  username: postgres
#  password: postgres
#  url: jdbc:postgresql://hexi_postgres:5440/nuclear
