spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/nuclear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088

system:
  files: D:\\sasmac\\files
  untargz: D:\\sasmac\\untargz
  datasource: \\HEXI-LT-2\\data,D:\\sasmac\\data

#  username: postgres
#  password: postgres
#  url: jdbc:postgresql://hexi_postgres:5440/nuclear
