spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://hexi_postgres:5432/nuclear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088
#    url: jdbc:postgresql://hexi_postgres:5440/nuclear
